---
- hosts: server
  tasks:
     - name: install git 
       yum:
        name: git
        state: present
     - name: Copy file with owner and permissions
       ansible.builtin.copy:
        src: test
        dest: /Desktop
        owner:  root
     - name: install apache server 
       yum: 
        name: httpd
        state: present

