---
- hosts: server
  tasks:
     - name: install apache server 
       ansible.builtin.service: 
        name: httpd
        state: started
        enabled: yes 
     - name: Copy file with owner and permissions
       ansible.builtin.copy:
        src: ~/test
        dest: ~/Desktop
        


